name: Generate Language Chart

on:
  push:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Python/Language_Chart  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install matplotlib pillow requests

      - name: Generate SVG + PNG
        run: python generate_chart.py

      - name: Commit updated charts
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -f Charts/languages.svg Charts/languages.png
          git diff --cached --quiet || git commit -m "🔄 Auto-update language chart"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
